name: Build and Deploy VuePress to Server

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # 选择要使用的 node 版本
          node-version: 20

      # 安装依赖
      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 运行构建脚本
      # Run the build script
      - name: Build VuePress site
        run: npm run docs:build

      # 部署到自定义服务器
      # Deploy to custom server
      - name: Deploy to Server via SSH
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT || 22 }}
          SOURCE: "src/.vuepress/dist/"
          TARGET: ${{ secrets.REMOTE_TARGET_DIR }}
          EXCLUDE: "/node_modules/, /.git/, /.github/"
          SCRIPT_BEFORE: |
            # 备份并清理旧目录
            if [ -d "${{ secrets.REMOTE_TARGET_DIR }}" ]; then
              echo "Backing up old deployment..."
              cp -r ${{ secrets.REMOTE_TARGET_DIR }} ${{ secrets.REMOTE_TARGET_DIR }}.backup.$(date +%Y%m%d_%H%M%S)
              echo "Cleaning old files..."
              rm -rf ${{ secrets.REMOTE_TARGET_DIR }}/*
            fi
            # 创建目标目录
            mkdir -p ${{ secrets.REMOTE_TARGET_DIR }}
          SCRIPT_AFTER: |
            # 设置正确的文件权限
            find ${{ secrets.REMOTE_TARGET_DIR }} -type f -exec chmod 644 {} \;
            find ${{ secrets.REMOTE_TARGET_DIR }} -type d -exec chmod 755 {} \;
            # 清理过期备份（保留最近3个）
            cd $(dirname ${{ secrets.REMOTE_TARGET_DIR }})
            ls -dt $(basename ${{ secrets.REMOTE_TARGET_DIR }}).backup.* 2>/dev/null | tail -n +4 | xargs rm -rf 2>/dev/null || true
            echo "Deployment completed successfully!"
